spring:
  application:
    name: z4nosql-catalogs-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    mongodb:
      uri: mongodb://${DB_USERNAME:yaksha}:${DB_PASSWORD:bloodyroar}@${DB_HOST:localhost}:${DB_PORT:27017}/${DB_DATABASE:db_z4f_catalogs}?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: ${ISSUER_URI:http://localhost:9090/realms/z4movies-dev}

  kafka:
    bootstrapServers: ${SERVER_KAFKA:localhost:9092}

server:
  port: ${PORT:7002}

logging:
  level:
    org:
      mongodb:
        driver: debug

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

openapi:
  service:
    title: NoSQL Catalogs Service
    version: 1.0.0
    url: http://localhost:8090

springdoc:
  api-docs:
    path: /z4nosql-catalogs-service/v3/api-docs
  swagger-ui:
    path: /z4nosql-catalogs-service/swagger-ui/index.html
    operationsSorter: method