spring:
  application:
    name: z4-catalogs-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:db_z4f_master_data}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:saksah}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: ${DDL_AUTO:create-drop} # Aquí controlas cuándo generar la base de datos
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: ${PORT:8001}

logging:
  level:
    org:
      hibernate:
        SQL: debug